export const LOAD_CUSTOMERS_SUCCESS = "LOAD_CUSTOMERS_SUCCESS";
export const LOAD_CUSTOMERS_FAILURE = "LOAD_CUSTOMERS_FAILURE";
export const LOAD_CUSTOMERS_PENDING = "LOAD_CUSTOMERS_PENDING";

export const LOAD_CUSTOMER_SUCCESS = "LOAD_CUSTOMER_SUCCESS";
export const LOAD_CUSTOMER_FAILURE = "LOAD_CUSTOMER_FAILURE";
export const LOAD_CUSTOMER_PENDING = "LOAD_CUSTOMER_PENDING";

export const ADD_CUSTOMER_SUCCESS = "ADD_CUSTOMER_SUCCESS";
export const ADD_CUSTOMER_FAILURE = "ADD_CUSTOMER_FAILURE";
export const ADD_CUSTOMER_PENDING = "ADD_CUSTOMER_PENDING";

export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER_FAILURE = "DELETE_CUSTOMER_FAILURE";
export const DELETE_CUSTOMER_PENDING = "DELETE_CUSTOMER_PENDING";

export const EDIT_CUSTOMER_SUCCESS = "EDIT_CUSTOMER_SUCCESS";
export const EDIT_CUSTOMER_FAILURE = "EDIT_CUSTOMER_FAILURE";
export const EDIT_CUSTOMER_PENDING = "EDIT_CUSTOMER_PENDING";

////////////////////////////////////////////////

export const LOAD_TEETIMES_SUCCESS = "LOAD_TEETIMES_SUCCESS";
export const LOAD_TEETIMES_FAILURE = "LOAD_TEETIMES_FAILURE";
export const LOAD_TEETIMES_PENDING = "LOAD_TEETIMES_PENDING";

export const LOAD_TEETIME_SUCCESS = "LOAD_TEETIME_SUCCESS";
export const LOAD_TEETIME_FAILURE = "LOAD_TEETIME_FAILURE";
export const LOAD_TEETIME_PENDING = "LOAD_TEETIME_PENDING";

export const ADD_TEETIME_SUCCESS = "ADD_TEETIME_SUCCESS";
export const ADD_TEETIME_FAILURE = "ADD_TEETIME_FAILURE";
export const ADD_TEETIME_PENDING = "ADD_TEETIME_PENDING";

export const DELETE_TEETIME_SUCCESS = "DELETE_TEETIME_SUCCESS";
export const DELETE_TEETIME_FAILURE = "DELETE_TEETIME_FAILURE";
export const DELETE_TEETIME_PENDING = "DELETE_TEETIME_PENDING";

export const EDIT_TEETIME_SUCCESS = "EDIT_TEETIME_SUCCESS";
export const EDIT_TEETIME_FAILURE = "EDIT_TEETIME_FAILURE";
export const EDIT_TEETIME_PENDING = "EDIT_TEETIME_PENDING";
